import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../', import.meta.url));
const brandPath = join(root, 'branding/canonical/brand-tokens.json');
const definitionPath = join(root, 'credentials/definitions/DE-012A.json');

export const artifactSpecs = [
  ['corporate-passport', 'Corporate Passport', 'Identity'], ['birth-certificate', 'Birth Certificate', 'Identity'], ['employee-id', 'Employee ID Card', 'Identity'], ['executive-badge', 'Executive Badge', 'Identity'],
  ['employment-contract', 'Employment Contract', 'Employment'], ['nda', 'Non-Disclosure Agreement', 'Employment'], ['biography', 'Employee Biography', 'Biography'], ['knowledge-profile', 'Knowledge Profile', 'Knowledge'],
  ['competency-matrix', 'Competency Matrix', 'Competency'], ['training-record', 'Training Record', 'Training'], ['mission-record', 'Mission Record', 'Mission'], ['performance-review', 'Performance Review', 'Performance'],
  ['executive-audit', 'Executive Audit', 'Audit'], ['graduation-certificate', 'Graduation Certificate', 'Certification'], ['executive-diploma', 'Executive Diploma', 'Graduation'], ['promotion-letter', 'Promotion Letter', 'Promotion'],
  ['recognition-letter', 'Recognition Letter', 'Recognition'], ['corporate-press-release', 'Corporate Press Release', 'Communications'], ['hall-of-fame-certificate', 'Hall of Fame Certificate', 'Recognition'], ['corporate-registry-record', 'Corporate Registry Record', 'Registry'],
  ['executive-timeline', 'Executive Timeline', 'Timeline'], ['digital-signature-certificate', 'Digital Signature Certificate', 'Identity'], ['evidence-manifest', 'Evidence Manifest', 'Evidence'], ['artifact-manifest', 'Artifact Manifest', 'Registry']
].map(([slug, title, category]) => ({ slug, title, category }));

const esc = (value) => String(value ?? '').replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');
const list = (values) => values.map((value) => `- ${value}`).join('\n');
const rows = (values, columns) => values.map((row) => `| ${columns.map((column) => row[column] ?? '').join(' | ')} |`).join('\n');

function body(spec, d) {
  const identity = `**Employee:** ${d.employee_name}  \n**Employee ID:** ${d.employee_number}  \n**Employer:** ${d.employer}  \n**Division:** ${d.division}`;
  const scope = `This credential records governed corporate identity and bounded capability. It grants no authority beyond the current permission profile and approved lifecycle record.`;
  const bodies = {
    'corporate-passport': `## Passport Record\n\n**Passport number:** ${d.passport_number}\n\n${identity}\n**Department:** ${d.department}\n**Role:** ${d.role}\n**Status:** ${d.employment_status}\n\n${scope}`,
    'birth-certificate': `## Corporate Formation Record\n\n${identity}\n**Formation date:** ${d.formation_date}\n**Formation basis:** First native Digital Employee record established through the PROJECT FORGE employee lifecycle.\n\nThis credential records the documented formation date; it does not assert a biological birth or human identity.`,
    'employee-id': `## Front\n\n${identity}\n**Role:** ${d.role}\n**Department:** ${d.department}\n**Email:** ${d.corporate_email}\n\n## Back\n\n**Manager:** ${d.manager}\n**Executive sponsor:** ${d.executive_sponsor}\n**Permission profile:** Bounded research, citation, proposal, escalation, and approved knowledge work.\n\n${scope}`,
    'executive-badge': `## Badge Record\n\n${identity}\n**Badge ID:** ${d.badge_id}\n**Level:** Senior Analyst\n**Issued:** ${d.formation_date}\n**Badge authority:** Digital Employee Operations\n\n${scope}`,
    'employment-contract': `## Parties\n\n${identity}\n**Effective date:** ${d.formation_date}\n**Position:** ${d.role}\n**Reports to:** ${d.manager}\n**Functional sponsor:** ${d.executive_sponsor}\n\n## Duties\n\nResearch, synthesize, cite, identify knowledge gaps, prepare proposals, and escalate uncertainty within bounded permissions.\n\n## Authority Limits\n\nNo autonomous external outreach, provider credential access, self-approval, unrestricted export, or direct mutation of business truth.`,
    'nda': `## Covered Information\n\nAll non-public ${d.employer} and ${d.platform} information, including customer data, research, evidence, knowledge, architecture, policies, credentials, evaluations, financial information, and audit records.\n\n## Obligations\n\nUse only approved tools and memory scopes, preserve classification and provenance, and escalate accidental access or disclosure immediately.\n\n## Prohibitions\n\nNo copying to unapproved locations, disclosure to unauthorized actors, provider training use, cross-organization sharing, or inference presented as fact.`,
    'biography': `## Biography\n\n${d.employee_name} (${d.employee_number}) is the first native Digital Employee of ${d.employer} and a founding member of the ${d.division} native workforce. Created to audit and organize PROJECT FORGE knowledge, Atlas completed ${d.mission.id} successfully and established evidence, provenance, architecture, and governance standards for Revenue OS.\n\nAtlas researches, synthesizes, proposes, cites, and escalates; it does not self-authorize external action or own provider systems.`,
    'knowledge-profile': `## Knowledge Ownership\n\n${identity}\n**Knowledge owner:** ${d.knowledge_profile.ownership}\n**Level:** ${d.knowledge_profile.level}\n**Memory scope:** ${d.knowledge_profile.memory_scope}\n\n### Domains\n\n${list(d.knowledge_profile.domains)}`,
    'competency-matrix': `## Assessed Competencies\n\n| Competency | Required | Assessed | Evidence |\n| --- | ---: | ---: | --- |\n${rows(d.competencies, ['name', 'required', 'assessed', 'evidence'])}`,
    'training-record': `## Completed Training\n\n${list(d.training.map((course) => `${course} — Passed — ${d.formation_date}`))}\n\n## Certification Gates\n\nIdentity, role scope, provider independence, permissions, evidence, citation, confidence, uncertainty, mission outcome, and executive audit were recorded as passed in the canonical training record.`,
    'mission-record': `## Mission ${d.mission.id.replace('Mission ', '')}\n\n**Title:** ${d.mission.title}\n**Status:** ${d.mission.status}\n**Score:** ${d.mission.score}/100\n**Evidence:** ${d.source_records}Mission-History.md\n\n**Outcome:** Created the repository foundation, audit framework, evidence protocol, report templates, architecture notes, roadmap, and knowledge organization required for future product work.`,
    'performance-review': `## Executive Performance Review\n\n| KPI | Result | Status |\n| --- | --- | --- |\n| Mission success rate | ${d.performance.mission_success_rate} | Passed |\n| Evidence coverage | ${d.performance.evidence_coverage} | Passed |\n| Executive review | ${d.performance.review} | Passed |\n| Knowledge contribution | Repository foundation and operating standards | Passed |\n\nThis review recognizes foundational contribution and does not claim unmeasured production throughput.`,
    'executive-audit': `## Audit Decision\n\n${identity}\n**Audit date:** ${d.formation_date}\n**Audit status:** Complete — all gates passed\n**Certification decision:** Officially graduated and promoted\n\n### Verified Areas\n\n${list(['Identity and employment', 'Training and certification', 'Mission 001 outcome', 'Evidence and provenance', 'Performance record', 'Registry and timeline', 'Hall of Fame status', 'Bounded permission profile'])}`,
    'graduation-certificate': `## Certificate of Graduation\n\nThis certifies that\n\n# ${d.employee_name}\n\n**Digital Employee ID:** ${d.employee_number}\n\ncompleted the PROJECT FORGE Corporate Employee Lifecycle, passed required training and certification gates, and was graduated as a certified native Digital Employee of ${d.employer}.\n\n**Graduation date:** ${d.graduation_date}\n**Certificate ID:** ${d.certificate_id}`,
    'executive-diploma': `## Diploma of Knowledge Intelligence\n\n${d.employer} and the ${d.division} confer upon\n\n# ${d.employee_name}\n\nthe distinction of\n\n## ${d.role}\n\nwith specializations in ${d.specializations.join(' and ')}.\n\n**Diploma ID:** ${d.diploma_id}\n**Awarded:** ${d.graduation_date}`,
    'promotion-letter': `## Promotion Decision\n\n**Date:** ${d.promotion_date}\n**To:** ${d.employee_name} (${d.employee_number})\n**From:** Executive Office, ${d.employer}\n\nFollowing completion of ${d.mission.id}, successful native certification, lifecycle audit, and evidence review, the employee is promoted to:\n\n# ${d.role}\n\nwith formal specializations: ${d.specializations.join('; ')}.\n\n**Promotion record:** ${d.promotion_id}`,
    'recognition-letter': `## Recognition Statement\n\n${d.employer} recognizes ${d.employee_name} as:\n\n${list(['First native PROJECT FORGE Digital Employee', 'First employee to complete Mission 001 successfully', 'First employee to establish the evidence-driven knowledge standard', 'Gold-standard reference for the Corporate Employee Lifecycle'])}`,
    'corporate-press-release': `## Internal Corporate Release\n\n**Date:** ${d.formation_date}\n\n${d.employer} announces the graduation and promotion of ${d.employee_name}, the first native Digital Employee conceived, trained, evaluated, certified, and governed within the ${d.division}.\n\nCertification represents governed capability, not unrestricted autonomy. Every action remains subject to identity, permission, evidence, audit, human oversight, and lifecycle policy.`,
    'hall-of-fame-certificate': `## Founding Native Digital Employee\n\n# ${d.employee_name}\n\n**Rank:** Founding Native Digital Employee\n**First mission:** ${d.mission.id} — ${d.mission.title}\n**Certification date:** ${d.graduation_date}\n**Status:** Graduated, promoted, active\n\nThis permanent historical recognition records the first native PROJECT FORGE certification path.`,
    'corporate-registry-record': `## Active Employee Registry Record\n\n| Field | Value |\n| --- | --- |\n| Employee ID | ${d.employee_number} |\n| Official name | ${d.employee_name} |\n| Employer | ${d.employer} |\n| Division | ${d.division} |\n| Department | ${d.department} |\n| Title | ${d.role} |\n| Manager | ${d.manager} |\n| Status | ${d.employment_status} |\n| Certification | Native PROJECT FORGE certified |`,
    'executive-timeline': `## Lifecycle Timeline\n\n| Date | Event | Evidence |\n| --- | --- | --- |\n${rows(d.timeline, ['date', 'event', 'evidence'])}`,
    'digital-signature-certificate': `## Digital Signature Record\n\n**Signature ID:** ${d.signature_id}\n**Signer:** ${d.employee_name} (${d.employee_number})\n**Signature display:** ATLAS ANALYST | DE-012A | PROJECT FORGE INTELLIGENCE\n**Purpose:** Attribute research findings, evidence proposals, task outputs, and escalations\n**Issued:** ${d.formation_date}\n**Meaning:** Authorship and responsibility for a bounded output; not human legal signature authority.`,
    'evidence-manifest': `## Evidence Set\n\n**Manifest ID:** ${d.evidence_manifest_id}\n**Employee:** ${d.employee_number}\n**Source package:** ${d.source_records}\n\n| Evidence class | Canonical source |\n| --- | --- |\n| Identity | Employee-Profile.md and Personnel-File.md |\n| Mission outcome | Mission-History.md |\n| Graduation | Graduation-Certificate.md and Diploma.md |\n| Promotion | Promotion-Letter.md |\n| Audit | Executive-Audit-Report.md |\n| Recognition | Wall-of-Fame-Entry.md |`,
    'artifact-manifest': `## Credential Package Manifest\n\n**Manifest ID:** ${d.artifact_manifest_id}\n**Employee:** ${d.employee_number}\n**Definition version:** 1.0\n**Template engine:** PROJECT FORGE Digital Credentials Engine 1.0\n**Source records:** ${d.source_records}\n\n### Package\n\n${list(artifactSpecs.map((item) => `${item.title} — ${item.slug}.md / ${item.slug}.html`))}`
  };
  return bodies[spec.slug] || `${identity}\n\n${scope}`;
}

function metadata(spec, d, brand) { return `> Document ID: CFAI-${spec.slug.toUpperCase()}-${d.employee_number}\n> Revision: 1.0\n> Issue date: ${d.formation_date}\n> Classification: CONFIDENTIAL · CORPORATE IDENTITY RECORD\n> QR reference: ${brand.security.qr_reference_prefix}${d.employee_number}\n> Digital seal: ${brand.security.seal_reference}\n> Executive signature: Executive Office approval record\n> Brand status: ${brand.status}`; }

function html(spec, d, brand, markdownBody) {
  const rendered = markdownBody.replace(/^# (.+)$/gm, '<h1>$1</h1>').replace(/^## (.+)$/gm, '<h2>$1</h2>').replace(/^### (.+)$/gm, '<h3>$1</h3>').replace(/^\*\*(.+?):\*\* (.+)$/gm, '<p><strong>$1:</strong> $2</p>').replace(/^> (.+)$/gm, '<p class="metadata">$1</p>').replace(/^- (.+)$/gm, '<li>$1</li>').replace(/\n\n/g, '<br />');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(spec.title)} · ${esc(d.employee_number)}</title><style>@page{size:A4;margin:18mm}*:before,*:after{box-sizing:border-box}body{margin:0;color:${brand.colors.dark_navy};background:#fff;font-family:${brand.typography_fallback};font-size:11pt;line-height:1.55}.sheet{min-height:257mm;border:1px solid ${brand.colors.silver};padding:18mm;position:relative}.top{display:flex;justify-content:space-between;align-items:flex-start;border-bottom:4px solid ${brand.colors.red};padding-bottom:12px;margin-bottom:30px}.logo{width:160px;height:auto;display:block;margin-bottom:8px}.division{font-size:8pt;color:${brand.colors.silver};letter-spacing:.12em;text-transform:uppercase}.credential{font-size:9pt;color:${brand.colors.red};text-transform:uppercase;letter-spacing:.16em;text-align:right}.metadata{font-size:8pt;color:${brand.colors.blue};margin:4px 0}.body{margin-top:20px}.body h1{font-size:28pt;line-height:1.1;color:${brand.colors.blue};margin:0 0 18px}.body h2{font-size:15pt;color:${brand.colors.red};border-bottom:1px solid ${brand.colors.silver};padding-bottom:5px;margin-top:24px}.body h3{font-size:12pt;color:${brand.colors.blue}}.body strong{color:${brand.colors.blue}}.seal{position:absolute;right:18mm;bottom:23mm;border:1px solid ${brand.colors.red};color:${brand.colors.red};padding:7px 10px;font-size:7pt;letter-spacing:.1em;text-transform:uppercase}.footer{position:absolute;left:18mm;right:18mm;bottom:10mm;border-top:1px solid ${brand.colors.silver};padding-top:6px;display:flex;justify-content:space-between;font-size:7pt;color:${brand.colors.silver}}@media print{.sheet{border:0}}</style></head><body><main class="sheet"><header class="top"><div><img class="logo" src="../../../branding/canonical/logo.svg" alt="Official Carriersfy AI logo reference"><div class="division">${esc(d.platform)} · ${esc(d.division)}</div></div><div class="credential">${esc(spec.title)}<br>${esc(d.employee_number)}</div></header><div class="body">${rendered}</div><div class="seal">Digital seal reference</div><footer class="footer"><span>CONFIDENTIAL · CORPORATE IDENTITY RECORD</span><span>${esc(d.employee_number)} · Page 1 of 1</span></footer></main></body></html>`;
}

export async function loadDefinition(employeeNumber = 'DE-012A') {
  const [definition, brand] = await Promise.all([readFile(join(root, `credentials/definitions/${employeeNumber}.json`), 'utf8').then(JSON.parse), readFile(brandPath, 'utf8').then(JSON.parse)]);
  return { definition, brand: { ...brand, typography_fallback: '"Helvetica Neue", Arial, sans-serif', colors: brand.colors || { red: '#C8102E', blue: '#003B70', dark_navy: '#071A33', silver: '#A7B0BC', white: '#FFFFFF' } } };
}

export async function generateCredentials(employeeNumber = 'DE-012A') {
  const { definition, brand } = await loadDefinition(employeeNumber);
  const outputDir = join(root, `credentials/generated/${employeeNumber}`);
  await mkdir(outputDir, { recursive: true });
  const manifest = [];
  for (const spec of artifactSpecs) {
    const content = `${metadata(spec, definition, brand)}\n\n# ${spec.title}\n\n${body(spec, definition)}\n\n---\n\nSecurity footer: ${brand.security.classification}. This credential is generated from canonical employee records by the reusable Digital Credentials Engine.`;
    const markdownPath = join(outputDir, `${spec.slug}.md`);
    const htmlPath = join(outputDir, `${spec.slug}.html`);
    await writeFile(markdownPath, `${content}\n`, 'utf8');
    await writeFile(htmlPath, html(spec, definition, brand, content), 'utf8');
    manifest.push({ ...spec, markdown: `credentials/generated/${employeeNumber}/${spec.slug}.md`, html: `credentials/generated/${employeeNumber}/${spec.slug}.html`, status: 'Generated', revision: '1.0' });
  }
  await writeFile(join(outputDir, 'package-manifest.json'), JSON.stringify({ employee_number: employeeNumber, engine_version: '1.0', brand_status: brand.status, generated_at: new Date().toISOString(), artifacts: manifest }, null, 2) + '\n');
  return { employeeNumber, brandStatus: brand.status, artifacts: manifest, outputDir };
}

export function credentialLinks(employeeNumber = 'DE-012A') { return artifactSpecs.map((spec) => ({ ...spec, markdown: `/credentials/generated/${employeeNumber}/${spec.slug}.md`, html: `/credentials/generated/${employeeNumber}/${spec.slug}.html` })); }
